### ISSUE TITLE
Make a dummy Redis DB for WarnServ

### ISSUE THREAD

**Issue by shymega** [vktec-irc/warnserv#7]
We should make a dummy Redis DB (example) for WarnServ, so prospective
developers can hack on WarnServ using sample data, which is different
from the production version on vKTec IRC.

**Comment by shymega** [comment]
Or, if the config tool does this - perhaps not?

**Comment by vktec** [comment]
The config tool creates a database which contains all the required configuration information for the program to run.

If I understand your suggestion correctly, you want a database which contains some sample users and warnings, however this wouldn't work very well, as the users would not actually exist, meaning that KICKs, bans, etc could not be tested using this data.

Rather than using a sample DB, contributors should set up the DB using the config tool, and then add warnings using the bot.

**Comment by shymega** [comment]
Yay, my first `wontfix`!
